### ISSUE TITLE
Nim 2.0 support

### ISSUE THREAD

**Issue by vanyle** [zevv/nimz3#7]
## nimz3 does not compile in Nim 2.0

In Nim 2.0, the way distinct is handled changed.
Because of this `nil` is not of type `distinct pointer`, the conversion need to be explicit.

This causes a compiler error for lines such as:
`proc to_Z3_ast(ctx: Z3_context, v: bool, sort: Z3_sort = nil): Z3_ast =`

 An explicit conversion needs to be added:

`proc to_Z3_ast(ctx: Z3_context, v: bool, sort: Z3_sort = nil.Z3_sort ): Z3_ast =`

**Comment by zevv** [comment]
Thanks. fixed.
